apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod2
  labels:
    env: dev
    version: v1
spec:
  containers:
  - name: my-nginx
    image: nginxdemos/hello:latest
    ports:
    - containerPort: 80