apiVersion: v1
kind: ReplicationController
metadata:
  name: my-repconprod
spec:
  replicas: 2
  selector:
    env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
      - name: my-pod
        image: nginxdemos/hello:latest
        ports:
        - containerPort: 80